# Generated by Django 4.1.3 on 2022-12-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_contacto_alter_noticia_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='avisos',
            new_name='desea_recibir_avisos',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='tipo_consulta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_de_consulta',
            field=models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']], default='0'),
        ),
    ]
